feat:新增《HTTP详解》文章
IDuxFE/weekly pull request #64
Opened 2021-11-12 14:50 UTC by wudu8

文章写作完成，预览地址：[《HTTP详解》](https://github.com/wudu8/weekly/blob/feat-docs-http_understand/article/2021/HTTP%E8%AF%A6%E8%A7%A3/HTTP%E8%AF%A6%E8%A7%A3.md)

2021-11-19 03:19 UTC, wongtsuizhen commented on article/2021/HTTP详解/HTTP详解.md
> +#### HTTP/0.9
各版本及特性写在一起吧，现在版本介绍只有0.9,1.10版本，但是特性有1.0,1.1,2.0，没有一一对应上，阅读起来稍微有点乱，可以例如:
### 版本特性
#### HTTP/0.9
&emsp;&emsp;HTTP协议的最初版本，请求方式只有GET，并且只能访问HTML格式的资源。
##### 特性

- xxxx
#### HTTP/1.0
&emsp;&emsp;请求行中引入了协议版本字段(http/1.0)；必须包含头部消息，不在局限仅能请求HTML格式的资源,可以支持多种数据格式、缓存等功能。
##### 特性

- xxxx

2021-11-22 02:11 UTC, wongtsuizhen requested changes
2个小问题修改下哈

2021-11-24 02:11 UTC, wongtsuizhen approved these changes

2021-11-24 02:37 UTC, Jouryjc commented
`WWW文件` 是什么意思？

2021-11-24 02:42 UTC, wudu8 commented
> `WWW文件`是什么英文？ `HTTP是一个基于TCP/IP通信协议来传递数据，默认端口是80。`有头没尾，是……啥？

我修改一下

2021-11-29 01:09 UTC, wongtsuizhen commented
题目修改下不要带详解吧，文字的内容可能更多是知识点的阐述 @wudu8

2021-12-13 01:05 UTC, merged